title : Computational Sensory-Motor Systems Lab
tagline: Computational neuromorphic approaches to perception and action.
institution:
  url: "https://www.jhu.edu"
  name: The Johns Hopkins University
department:
  url: "https://ece.jhu.edu"
  name: Electrical & Computer Engineering
permalink: none
markdown: kramdown
